# Ridge models with Palmer Penguins

## 1. Setup
If needed, uncomment and run the installation line once. Restart the kernel after installation if requested. `palmerpenguins` includes the data, so loading it does not require a separate data download.

In [1]:
import numpy as np
import pandas as pd
from palmerpenguins import load_penguins
from sklearn.linear_model import Ridge, RidgeClassifier, RidgeCV, RidgeClassifierCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from plotnine import *

### Load data

In [2]:
penguins = load_penguins().dropna()
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007

## Predict body mass

In [3]:
mass_features = ["bill_length_mm", "bill_depth_mm", "flipper_length_mm"]
X_mass = penguins[mass_features]
y_mass = penguins["body_mass_g"]

### Train-Test Split

In [4]:
X_mass_train, X_mass_test, y_mass_train, y_mass_test = train_test_split(
    X_mass, y_mass, test_size=0.20, random_state=909
)

### Set Model

In [5]:
ridge_model = Ridge(alpha=1.0)

### Fit the model

In [6]:
ridge_model.fit(X_mass_train, y_mass_train)

Ridge()

### Make predictions

In [7]:
mass_predictions = ridge_model.predict(X_mass_test)
display(pd.DataFrame({
    "observed_g": y_mass_test,
    "predicted_g": mass_predictions,
    "residual_g": y_mass_test - mass_predictions,
}).head().round(1))

     observed_g  predicted_g  residual_g
318      3550.0       4038.7      -488.7
73       4150.0       4060.8        89.2
222      4750.0       4972.1      -222.1
258      4700.0       4637.1        62.9
238      4600.0       5043.1      -443.1

### Calculate Error

In [8]:
mse_mass = mean_squared_error(y_mass_test, mass_predictions)
mae_mass = mean_absolute_error(y_mass_test, mass_predictions)
print(mse_mass)
print(mae_mass)

154633.81712926834
318.0187943672721

## Classify Species

### Setting Data

In [9]:
species_features = [
    "bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g"
]
mass_features = ["bill_length_mm", "bill_depth_mm", "flipper_length_mm"]
X_mass = penguins[mass_features]
y_mass = penguins["body_mass_g"]
species_data = penguins.dropna(subset=["species"]).copy()
X_species = penguins[species_features]
y_species = pd.Categorical(penguins["species"])

### Train-Test Split

In [10]:
X_species_train, X_species_test, y_species_train, y_species_test = train_test_split(
    X_species, y_species, test_size=0.20, random_state=909
)

### Specify Model

In [11]:
species_model = RidgeClassifier(alpha=1.0)

### Fit the classifier

In [12]:
species_model.fit(X_species_train, y_species_train)

RidgeClassifier()

### Predict species labels

In [13]:
species_predict = species_model.predict(X_species_test)

### Error Rate

In [14]:
(species_predict == y_species_test).mean()

np.float64(1.0)

## Cross-Validation

### Ridge Regression

#### Create $\alpha$'s

In [15]:
alphas = np.logspace(-3, 2, 100)

#### Set Model

In [16]:
mass_model_cv = RidgeCV(alphas=alphas)

#### Fit Model

In [17]:
mass_model_cv.fit(X_mass, y_mass)

RidgeCV(alphas=array([1.00000000e-03, 1.12332403e-03, 1.26185688e-03, 1.41747416e-03,
       1.59228279e-03, 1.78864953e-03, 2.00923300e-03, 2.25701972e-03,
       2.53536449e-03, 2.84803587e-03, 3.19926714e-03, 3.59381366e-03,
       4.03701726e-03, 4.53487851e-03, 5.09413801e-03, 5.72236766e-03,
       6.42807312e-03, 7.22080902e-03, 8.11130831e-03, 9.11162756e-03,
       1.02353102e-02, 1.14975700e-0...
       6.89261210e+00, 7.74263683e+00, 8.69749003e+00, 9.77009957e+00,
       1.09749877e+01, 1.23284674e+01, 1.38488637e+01, 1.55567614e+01,
       1.74752840e+01, 1.96304065e+01, 2.20513074e+01, 2.47707636e+01,
       2.78255940e+01, 3.12571585e+01, 3.51119173e+01, 3.94420606e+01,
       4.43062146e+01, 4.97702356e+01, 5.59081018e+01, 6.28029144e+01,
       7.05480231e+01, 7.92482898e+01, 8.90215085e+01, 1.00000000e+02]))

#### Best Alpha

In [18]:
print(mass_model_cv.alpha_)

100.0

### Ridge Classification

#### Setting Alphas

In [19]:
alphas = np.logspace(-3, 2, 100)

#### Setting Model

In [20]:
species_model_cv = RidgeClassifierCV(alphas=alphas)

#### Fitting Model

In [21]:
species_model_cv.fit(X_species, y_species)

RidgeClassifierCV(alphas=array([1.00000000e-03, 1.12332403e-03, 1.26185688e-03, 1.41747416e-03,
       1.59228279e-03, 1.78864953e-03, 2.00923300e-03, 2.25701972e-03,
       2.53536449e-03, 2.84803587e-03, 3.19926714e-03, 3.59381366e-03,
       4.03701726e-03, 4.53487851e-03, 5.09413801e-03, 5.72236766e-03,
       6.42807312e-03, 7.22080902e-03, 8.11130831e-03, 9.11162756e-03,
       1.02353102e-02, 1.1...
       6.89261210e+00, 7.74263683e+00, 8.69749003e+00, 9.77009957e+00,
       1.09749877e+01, 1.23284674e+01, 1.38488637e+01, 1.55567614e+01,
       1.74752840e+01, 1.96304065e+01, 2.20513074e+01, 2.47707636e+01,
       2.78255940e+01, 3.12571585e+01, 3.51119173e+01, 3.94420606e+01,
       4.43062146e+01, 4.97702356e+01, 5.59081018e+01, 6.28029144e+01,
       7.05480231e+01, 7.92482898e+01, 8.90215085e+01, 1.00000000e+02]))

#### Best $\alpha$

In [22]:
print(species_model_cv.alpha_)

9.770099572992246